version: "3.8"

services:
  mortgage-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mortgage-app-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: unless-stopped
