spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: testdb
    password: testdb
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

  h2:
    console:
      enabled: true
      path: /h2-console

  jackson:
    default-property-inclusion: NON_NULL
  sql:
    init:
      mode: always
      schema-locations: classpath:db-scripts/add-mortgage-schema.sql
      data-locations: classpath:db-scripts/add-mortgage-rates.sql

