spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: testdb
    password: testdb
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      schema-locations: classpath:db-scripts/add-mortgage-schema.sql
      data-locations: classpath:db-scripts/add-mortgage-rates.sql
    

